const SET_LOADING = "SET_LOADING";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
const LOGOUT_USER = "LOGOUT_USER";
export { SET_LOADING, REGISTER_USER_SUCCESS, REGISTER_USER_ERROR, LOGOUT_USER };
